/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as Char91__mockupChar93PreviewSplatRouteImport } from './routes/[__mockup].preview.$'
import { Route as Char91__componentChar93PreviewSplatRouteImport } from './routes/[__component].preview.$'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const Char91__mockupChar93PreviewSplatRoute =
  Char91__mockupChar93PreviewSplatRouteImport.update({
    id: '/__mockup/preview/$',
    path: '/__mockup/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91__componentChar93PreviewSplatRoute =
  Char91__componentChar93PreviewSplatRouteImport.update({
    id: '/__component/preview/$',
    path: '/__component/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/passport': typeof PassportRoute
  '/scan': typeof ScanRoute
  '/shop': typeof ShopRouteWithChildren
  '/shop/': typeof ShopIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/passport': typeof PassportRoute
  '/scan': typeof ScanRoute
  '/shop': typeof ShopIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/passport': typeof PassportRoute
  '/scan': typeof ScanRoute
  '/shop': typeof ShopRouteWithChildren
  '/shop/': typeof ShopIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/passport'
    | '/scan'
    | '/shop'
    | '/shop/'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/passport'
    | '/scan'
    | '/shop'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
  id:
    | '__root__'
    | '/'
    | '/passport'
    | '/scan'
    | '/shop'
    | '/shop/'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PassportRoute: typeof PassportRoute
  ScanRoute: typeof ScanRoute
  ShopRoute: typeof ShopRouteWithChildren
  Char91__componentChar93PreviewSplatRoute: typeof Char91__componentChar93PreviewSplatRoute
  Char91__mockupChar93PreviewSplatRoute: typeof Char91__mockupChar93PreviewSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/__mockup/preview/$': {
      id: '/__mockup/preview/$'
      path: '/__mockup/preview/$'
      fullPath: '/__mockup/preview/$'
      preLoaderRoute: typeof Char91__mockupChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__component/preview/$': {
      id: '/__component/preview/$'
      path: '/__component/preview/$'
      fullPath: '/__component/preview/$'
      preLoaderRoute: typeof Char91__componentChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShopRouteChildren {
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PassportRoute: PassportRoute,
  ScanRoute: ScanRoute,
  ShopRoute: ShopRouteWithChildren,
  Char91__componentChar93PreviewSplatRoute:
    Char91__componentChar93PreviewSplatRoute,
  Char91__mockupChar93PreviewSplatRoute: Char91__mockupChar93PreviewSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
